# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Linter
gem 'rubocop', require: false

# GitHub Pages and Jekyll Support
gem 'github-pages', group: :jekyll_plugins
gem 'webrick'

# Ruby on Rails
gem 'rails'
