# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Linter
gem 'rubocop', require: false

# GitHub Pages and Jekyll Support
gem 'github-pages', group: :jekyll_plugins
gem 'webrick'

# Ruby on Rails
gem 'rails'

# Use installed version of rdoc
rdoc_spec = Gem::Specification.find_all_by_name('rdoc').first
if rdoc_spec
  gem 'rdoc', rdoc_spec.version.to_s
else
  gem 'rdoc'
end
